site_name: learn-kotlin Documentation
theme: "material"
markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - smarty
  - wikilinks
  - codehilite:
      linenums: True
extra:
  palette:
    primary: "#087da1"
    accent: "#00a889"
  font:
    text: "Source Sans Pro"

repo_name: "luismayta/learn-kotlin"
repo_url: "https://github.com/luismayta/learn-kotlin"
copyright: 'Copyright © 2021 <a href="https://luismayta.dev">luismayta</a>'

google_analytics:
  - ""
  - "auto"
